version: '3'

volumes:
  pg_data:
  static:
  redis_data:

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  postgres_db:
    container_name: pg_container
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/currency_converter_backend
    container_name: backend_container
    env_file: .env
    volumes:
      - static:/backend_static/
    depends_on:
      - postgres_db
      - redis
  
  gateway:
    image: ${DOCKER_USERNAME}/currency_converter_gateway
    container_name: gateway_container
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend
  
  celery_worker:
    image: ${DOCKER_USERNAME}/currency_converter_backend
    container_name: celery_worker_container
    command: celery -A currency_converter worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - backend
      - postgres_db

  celery_beat:
    image: ${DOCKER_USERNAME}/currency_converter_backend
    container_name: celery_beat_container
    command: celery -A currency_converter beat --loglevel=info
    env_file: .env
    volumes: 
      - pg_data:/var/lib/postgresql/data
      - redis_data:/data
    depends_on:
      - redis
      - backend
      - postgres_db